/**
 * PDF Exporter for Contrast Checker
 *
 * Generates a minimal, valid PDF 1.3 report containing the serialised
 * tool state. The document uses Helvetica and is designed to be
 * printer-friendly.
 *
 * This is a dependency-free, client-side generator — no external PDF
 * libraries are required.
 */

import type { Exporter } from "@itsjust/core";

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Compute the exact byte offset of each object and build a correct
 * cross-reference table so the PDF is valid.
 */
function buildPdf(stateJson: string): Uint8Array {
  const stateLabel = (stateJson || "{}").slice(0, 160).replace(/[()\\]/g, "\\$&");

  const encoder = new TextEncoder();

  const header = encoder.encode("%PDF-1.3\n%\xE2\xE3\xCF\xD3\n");
  const dump = (s: string) => encoder.encode(s);

  // ── Objects ──────────────────────────────────────────────────────
  const obj1 = encoder.encode("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
  const obj2 = encoder.encode("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
  const obj3 = encoder.encode(
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
  );

  const streamText = `BT
/F1 24 Tf
50 740 Td
(Contrast Checker Report) Tj
ET
BT
/F1 10 Tf
50 700 Td
(Generated by ItsJust Contrast Checker) Tj
50 680 Td
(State: ${stateLabel}) Tj
ET`;
  const streamLen = encoder.encode(streamText).length;
  const obj4 = encoder.encode(
    `4 0 obj\n<< /Length ${streamLen} >>\nstream\n${streamText}\nendstream\nendobj\n`,
  );

  const obj5 = encoder.encode("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n");

  const objects = [obj1, obj2, obj3, obj4, obj5];

  // ── Cross-reference table with exact byte offsets ────────────────
  let cursor = header.length;
  const xrefRows: string[] = ["0000000000 65535 f \n"];
  for (const obj of objects) {
    xrefRows.push(
      cursor.toString().padStart(10, "0") + " 00000 n \n",
    );
    cursor += obj.length;
  }
  const xrefStr = `xref\n0 ${xrefRows.length}\n${xrefRows.join("")}`;
  const xrefBytes = dump(xrefStr);

  const trailerStr = `trailer\n<< /Size ${xrefRows.length} /Root 1 0 R >>\nstartxref\n${cursor}\n%%EOF\n`;
  const trailerBytes = dump(trailerStr);

  // ── Assemble ─────────────────────────────────────────────────────
  const chunks = [header, ...objects, xrefBytes, trailerBytes];
  const totalLen = chunks.reduce((sum, c) => sum + c.length, 0);
  const result = new Uint8Array(totalLen);
  let pos = 0;
  for (const chunk of chunks) {
    result.set(chunk, pos);
    pos += chunk.length;
  }
  return result;
}

// ── Exporter ───────────────────────────────────────────────────────────────

export const exporter: Exporter = {
  format: "pdf",
  export: async (_element, options, stateSerializer) => {
    try {
      const serializer = stateSerializer?.() || "{}";
      const pdfBytes = buildPdf(serializer);
      const blob = new Blob([new Uint8Array(pdfBytes)], { type: "application/pdf" });

      return {
        success: true,
        data: blob,
        filename:
          options?.filename ?? `contrast-check-report-${Date.now()}.pdf`,
        format: "pdf",
      };
    } catch (error) {
      console.error("[PDF Exporter]", error);
      return {
        success: false,
        data: null,
        filename: options?.filename ?? `contrast-check-report-${Date.now()}`,
        format: "pdf",
        error: error instanceof Error ? error.message : "PDF export failed",
      };
    }
  },
};

export default exporter;